[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
property_registry = "5d3VC6f3bRHUZcos7GdA6fmj8Xtuhf2oSCDD988kmDWs"
rental_agreement = "FD4wJxjtivZBoujfYACCUNo1D7ygsbn9Gx26cU1UqPXV"
escrow = "7aa5fKvc4ejGWZdbxn8DmH5RVhofgwURXibcp3RtstAg"

[programs.localnet]
property_registry = "5d3VC6f3bRHUZcos7GdA6fmj8Xtuhf2oSCDD988kmDWs"
rental_agreement = "FD4wJxjtivZBoujfYACCUNo1D7ygsbn9Gx26cU1UqPXV"
escrow = "7aa5fKvc4ejGWZdbxn8DmH5RVhofgwURXibcp3RtstAg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
